train-models:
  quail:
    data: quail_race_fmt
    files:
      - train.json
      - dev.json
  quail-no-empty-answers:
    data: quail_no_empty_answers
    files:
      - train.json
      - dev.json
  race:
    data: RACE
    files:
      - train
      - dev
quail:
  train:
    do_train: true
    num_train_epochs: 2
    per_device_train_batch_size: 2
    model_type: bert
    task_name: generic
    fp16: true
    fp16_opt_level: O1
    max_seq_length: 484
    gradient_accumulation_steps: 8
    learning_rate: 5e-05
    warmup_steps: 500
  eval:
    do_train: false
    do_eval: true
    per_device_eval_batch_size: 8
    model_type: bert
    task_name: generic
    fp16: true
    fp16_opt_level: O1
    max_seq_length: 484
    gradient_accumulation_steps: 8
    learning_rate: 5e-05
    warmup_steps: 500
quail-no-empty-answers:
  train:
    do_train: true
    num_train_epochs: 2
    per_device_train_batch_size: 2
    model_type: bert
    task_name: generic
    fp16: true
    fp16_opt_level: O1
    max_seq_length: 484
    gradient_accumulation_steps: 8
    learning_rate: 5e-05
    warmup_steps: 500
  eval:
    do_train: false
    do_eval: true
    per_device_eval_batch_size: 8
    model_type: bert
    task_name: generic
    fp16: true
    fp16_opt_level: O1
    max_seq_length: 484
    gradient_accumulation_steps: 8
    learning_rate: 5e-05
    warmup_steps: 500
race:
  train:
    do_train: true
    num_train_epochs: 2
    per_device_train_batch_size: 2
    model_type: bert
    task_name: race
    fp16: true
    fp16_opt_level: O1
    max_seq_length: 484
    gradient_accumulation_steps: 8
    learning_rate: 5e-05
    warmup_steps: 500
  eval:
    do_train: false
    do_eval: true
    per_device_eval_batch_size: 8
    model_type: bert
    task_name: race
    fp16: true
    fp16_opt_level: O1
    max_seq_length: 484
    gradient_accumulation_steps: 8
    learning_rate: 5e-05
    warmup_steps: 500

