train:
  do_train: true
  num_train_epochs: 2
  per_device_train_batch_size: 2
  model_type: bert
  task_name: generic
  fp16: true
  fp16_opt_level: O1
  max_seq_length: 484
  gradient_accumulation_steps: 8
  learning_rate: 5e-05
  warmup_steps: 500
eval:
  do_train: false
  do_eval: true
  per_device_eval_batch_size: 8
  model_type: bert
  task_name: generic
  fp16: true
  fp16_opt_level: O1
  max_seq_length: 484
  gradient_accumulation_steps: 8
  learning_rate: 5e-05
  warmup_steps: 500

