vars:
  - ../../params/format.yaml

stages:
  format-quail-to-race:
    foreach: ${quail.splits}
    do:
      wdir: ../..
      cmd: src/etl/preprocess_quail_to_race.py data/quail/${item.data} data/quail/${item.answers}
        -o data/${quail.format.output}/${item.data}
      deps:
      - data/quail/${item.data}
      - data/quail/${item.answers}
      - src/etl/preprocess_quail_to_race.py
      outs:
      - data/${quail.format.output}/${item.data}
  split-quail:
    wdir: ../..
    cmd: src/etl/split_dataset.py --data_path data/${quail.format.output} --overwrite
      --output_dir data/${quail.split-data.output}
      --outputs ${quail.splits.train.data} ${quail.splits.dev.data}
      --move ${quail.splits.dev.data} ${quail.transform-splits.test.data}
      --no_answer_text "${quail.no_answer_text}"
      --proportion 0.75
      --split train
      --task generic
    deps:
      - data/${quail.format.output}/${quail.splits.train.data}
      - data/${quail.format.output}/${quail.splits.dev.data}
    outs:
      - data/${quail.split-data.output}/${quail.splits.train.data}
      - data/${quail.split-data.output}/${quail.splits.dev.data}
      - data/${quail.split-data.output}/${quail.transform-splits.test.data}
  format-quail-no-empty-answers:
    foreach: ${quail.transform-splits}
    do:
      wdir: ../..
      cmd: python src/etl/choices/reformat_dataset.py -d data/${quail.split-data.output} -o data/${quail.transform.output}
        -s ${key} --no_answer_text "${quail.no_answer_text}" --task generic
      deps:
      - data/${quail.split-data.output}
      - src/etl/choices/reformat_dataset.py
      outs:
      - data/${quail.transform.output}/${item.data}
  format-race:
    foreach: ${race.splits}
    do:
      wdir: ../..
      cmd: python src/etl/choices/reformat_dataset.py -d data/RACE/ -o data/${race.format.output}
        -s ${key} --no_answer_text "${race.no_answer_text}" --task race --mask --proportion 0.0
      deps:
      - data/RACE/${item.orig_data}
      - src/etl/choices/reformat_dataset.py
      outs:
      - data/${race.format.output}/${item.data}
  split-race:
    wdir: ../..
    cmd: src/etl/split_dataset.py --data_path data/${race.format.output}
      --overwrite
      --output_dir data/${race.split-data.output}
      --outputs ${race.splits.train.data} ${race.splits.dev.data}
      --move ${race.splits.dev.data} ${race.transform-splits.test.data}
      --proportion 0.75
      --split train
      --task generic
    deps:
      - data/${race.format.output}/${race.splits.train.data}
      - data/${race.format.output}/${race.splits.dev.data}
    outs:
      - data/${race.split-data.output}/${race.splits.train.data}
      - data/${race.split-data.output}/${race.splits.dev.data}
      - data/${race.split-data.output}/${race.transform-splits.test.data}
  format-race-with-empty-answers:
    foreach: ${race.transform-splits}
    do:
      wdir: ../..
      cmd: python src/etl/choices/reformat_dataset.py -d data/${race.split-data.output} -o data/${race.transform.output}
        -s ${key} --no_answer_text "${race.no_answer_text}" --task generic --mask --mask_correct --proportion 0.11
      deps:
      - data/${race.split-data.output}/${item.data}
      - src/etl/choices/reformat_dataset.py
      outs:
      - data/${race.transform.output}/${item.data}
  # format-quail-no-empty-answers:
  #   foreach: ${quail.splits}
  #   do:
  #     wdir: ../..
  #     cmd: python src/etl/choices/reformat_dataset.py -d data/${quail.format.output} -o data/${quail.transform.output}
  #       -s ${key} --no_answer_text "${quail.no_answer_text}" --keep_matching_text --index_list_path
  #       data/${quail.transform.output}/${key}_index_list.json
  #     deps:
  #     - data/${quail.format.output}
  #     - src/etl/choices/reformat_dataset.py
  #     outs:
  #     - data/${quail.transform.output}/${item.data}
  #     - data/${quail.transform.output}/${key}_index_list.json
  # format-quail-no-empty-answers-removed:
  #   foreach: ${quail.splits}
  #   do:
  #     wdir: ../..
  #     cmd: python src/etl/choices/reformat_dataset.py -d data/${quail.format.output} -o data/quail_empty_answers_removed
  #       -s ${key} --no_answer_text "${quail.no_answer_text}"
  #     deps:
  #     - data/${quail.format.output}
  #     - src/etl/choices/reformat_dataset.py
  #     outs:
  #     - data/quail_empty_answers_removed/${key}.json
