vars:
  - ../../params/format.yaml

stages:
  format-quail-to-race:
    foreach: ${quail.splits}
    do:
      wdir: ../..
      cmd: src/etl/preprocess_quail_to_race.py data/quail/${item.data} data/quail/${item.answers}
        -o data/${quail.format.output}/${item.data}
      deps:
      - data/quail/${item.data}
      - data/quail/${item.answers}
      - src/etl/preprocess_quail_to_race.py
      outs:
      - data/${quail.format.output}/${item.data}
  format-quail-no-empty-answers:
    foreach: ${quail.splits}
    do:
      wdir: ../..
      cmd: python src/etl/choices/reformat_dataset.py -d data/${quail.transform.input} -o data/${quail.transform.output}
        -s ${key} --no_answer_text "${quail.no_answer_text}" --task generic
      deps:
      - data/${quail.transform.input}
      - src/etl/choices/reformat_dataset.py
      outs:
      - data/${quail.transform.output}/${item.data}
  format-race:
    foreach: ${race.splits}
    do:
      wdir: ../..
      cmd: python src/etl/choices/reformat_dataset.py -d data/RACE/ -o data/${race.format.output}
        -s ${key} --no_answer_text "${race.no_answer_text}" --task race --mask --proportion 0.0
      deps:
      - data/RACE/${item.orig_data}
      - src/etl/reformat_dataset.py
      outs:
      - data/${race.format.output}/${item.data}
  format-race-with-empty-answers:
    foreach: ${race.splits}
    do:
      wdir: ../..
      cmd: python src/etl/choices/reformat_dataset.py -d data/${race.transform.input} -o data/${race.transform.output}
        -s ${key} --no_answer_text "${race.no_answer_text}" --task generic --mask --mask_correct --proportion 0.25
      deps:
      - data/${race.transform.input}/${item.data}
      - src/etl/choices/reformat_dataset.py
      outs:
      - data/${race.transform.output}/${item.data}
  # format-quail-no-empty-answers:
  #   foreach: ${quail.splits}
  #   do:
  #     wdir: ../..
  #     cmd: python src/etl/choices/reformat_dataset.py -d data/${quail.format.output} -o data/${quail.transform.output}
  #       -s ${key} --no_answer_text "${quail.no_answer_text}" --keep_matching_text --index_list_path
  #       data/${quail.transform.output}/${key}_index_list.json
  #     deps:
  #     - data/${quail.format.output}
  #     - src/etl/choices/reformat_dataset.py
  #     outs:
  #     - data/${quail.transform.output}/${item.data}
  #     - data/${quail.transform.output}/${key}_index_list.json
  # format-quail-no-empty-answers-removed:
  #   foreach: ${quail.splits}
  #   do:
  #     wdir: ../..
  #     cmd: python src/etl/choices/reformat_dataset.py -d data/${quail.format.output} -o data/quail_empty_answers_removed
  #       -s ${key} --no_answer_text "${quail.no_answer_text}"
  #     deps:
  #     - data/${quail.format.output}
  #     - src/etl/choices/reformat_dataset.py
  #     outs:
  #     - data/quail_empty_answers_removed/${key}.json