vars:
  - ../../../params/models.yaml

stages:
  bert-train:
    foreach: ${train-models}
    do:
      wdir: ../../..
      cmd: src/processing/run.sh params/model-params.yaml:${key}.train --data_dir "data/${key}"
        --model_name_or_path "data/models/${item.model}"
        --output_dir "data/models/bert-train-${key}"
        --metrics_dir "data/metrics/bert-train-${key}"
        --results_dir "data/results/bert-train-${key}"
        --cache_dir "/tmp"
      deps:
      - data/models/${item.model}
      - src/processing/run.sh
      # avoid cycles
      - data/${item.data}/${item.files[0]}
      - data/${item.data}/${item.files[1]}
      params:
      - params/model-params.yaml:
        - ${key}.train
      outs:
        # - data/${item.data}/cached_train_BertTokenizer_484_race
        # - data/${item.data}/cached_train_BertTokenizer_484_race.lock
      - data/models/bert-train-${key}/config.json
      - data/models/bert-train-${key}/pytorch_model.bin
      - data/models/bert-train-${key}/special_tokens_map.json
      - data/models/bert-train-${key}/tokenizer_config.json
      - data/models/bert-train-${key}/training_args.bin
      - data/models/bert-train-${key}/vocab.txt
      - data/results/bert-train-${key}/train_nbest_predictions.json
      - data/results/bert-train-${key}/train_predictions.json
      - data/results/bert-train-${key}/eval_nbest_predictions.json
      - data/results/bert-train-${key}/eval_predictions.json
      metrics:
      - data/metrics/bert-train-${key}/eval_metrics.json
      - data/metrics/bert-train-${key}/train_metrics.json

